# Generated by Django 4.1.4 on 2023-01-24 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_verified_email_emailverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverification',
            old_name='users',
            new_name='user',
        ),
    ]
